CREATE TABLE users (
    ID int,
    username varchar(255) NOT NULL,
    PRIMARY KEY (ID)
);

INSERT INTO users VALUES (1, 'Huey');
INSERT INTO users VALUES (2, 'Dewey');
INSERT INTO users VALUES (3, 'Louie');
INSERT INTO users VALUES (11, 'John Rambo');


CREATE TABLE walls (
    ID int /*GENERATED BY DEFAULT AS IDENTITY*/,
    begin_x int,
    begin_y int,
    end_x int,
    end_y int 
);

CREATE TABLE desks (
    ID int PRIMARY KEY,
    x int,
    y int
);

CREATE TABLE reservations(
    user_id int REFERENCES users (ID),
    desk_id int REFERENCES desks (ID),
    date date 
);


insert into desks values ( 100, 20, 10);
insert into desks values ( 101, 20, 30);
insert into desks values ( 102, 70, 10);
insert into desks values ( 103, 60, 30);
insert into desks values ( 104, 90, 10);
insert into desks values ( 105, 110, 10);
insert into desks values ( 106, 130, 10);
insert into desks values ( 107, 100, 40);
insert into desks values ( 108, 120, 40);
insert into desks values ( 109, 130, 30);
insert into desks values ( 110, 150, 20);
insert into desks values ( 111, 150, 40);

insert into walls values( 1, 0, 0, 190, 0);
insert into walls values( 2, 0, 0, 0, 50);
insert into walls values( 3, 50, 0, 50, 50);
insert into walls values( 4, 150, 0, 150, 50);
insert into walls values( 5, 0, 50, 30, 50);
insert into walls values( 6, 40, 50, 70, 50);
insert into walls values( 7, 80, 50, 130, 50);
insert into walls values( 8, 140, 50, 170, 50);
insert into walls values( 9, 180, 50, 190, 50);

insert into reservations values (1, 103, '2020-11-18');
insert into reservations values (2, 105, '2020-11-18');


